version: '3.3'

services:
  postgres_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres_db:5432/postgres -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./../migration:/flyway/sql
    depends_on:
      - postgres_db
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_db:
    driver: local
